# 配置 Zipkin 客户端端口
server:
  port: 8090

#spring.application.name 配置当前服务注册在eureka server 上的名字
#spring.sleuth.web.client.enabled 配置是否开启请求跟踪
#spring.sleuth.sampler.probability 设置采样比例，默认1.0
#spring.zipkin.base-url 配置zipkin server 地址
spring:
  application:
    name: zipkinclient
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9090/

#配置注册中心的访问地址（启动后，当前微服务会找到注册中心进行注册）
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/