#配置configserver 端口
server:
  port: 8762

#spring.application.name 配置当前服务注册在eureka server 上的名字
#spring.profiles.active 配置Config 配置中心的配置文件获取方式 "native"=本地获取
#spring.cloud.config.server.native.search-locations 配置Config 配置中心的  本地配置文件存放路径
#（classpath：指向的是resources目录下，所以需要在此目录下新建一个名为：shared文件存放配置文件，shared里的配置文件是给其他服务用的）
spring:
  application:
    name: nativeconfigserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
